apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: tle728-db-vol
  name: tle728-db-vol
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage #Snagged issue here, had to follow https://www.digitalocean.com/community/tutorials/how-to-deploy-a-php-application-with-kubernetes-on-ubuntu-16-04#step-3-%E2%80%94-creating-the-persistent-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tle728-cs4783-spring2021-db
  labels:
    app: cs4783-spring2021-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs4783-spring2021-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cs4783-spring2021-db
    spec:
      containers:
      - args:
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_DATABASE
          value: property
        - name: MYSQL_PASSWORD
          value: secretPassword
        - name: MYSQL_ROOT_PASSWORD
          value: eggs
        - name: MYSQL_USER
          value: tle728
        image: 0295/cs4783-spring2021:latest
        ports:
          - containerPort: 3306
        imagePullPolicy: Always
        name: tle728-db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: tle728-db-vol
      hostname: db
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: tle728-db-vol
        persistentVolumeClaim:
          claimName: tle728-db-vol
