apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: tle728-db-vol
  name: tle728-db-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
